services:
  postgres:
    image: postgres:16
    container_name: cloudsecops-postgres
    environment:
      POSTGRES_DB: cloudsecops_db
      POSTGRES_USER: cloudsecops_user
      POSTGRES_PASSWORD: cloudsecops_password
    ports:
      - "5432:5432"
    volumes:
      - cloudsecops_pgdata:/var/lib/postgresql/data

volumes:
  cloudsecops_pgdata: